### PR TITLE
DOCS: deprecate database_provides and database_requires libs

### PR DESCRIPTION
**Pull request by beliaev-maksim**
deprecate database_provides and database_requires libs in favor of data_interfaces

limit README.md line length to 99 chars

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
I do not understand why linter is failing, locally:
  lint: commands succeeded
  unit: commands succeeded
  congratulations :)

**Comment by beliaev-maksim** [comment]
@welpaolo @marceloneppel 
can you please review ?

**Review by deusebio — APPROVED** [review]
Looks good! Let me see if I understand why linting is failing

**Comment by dragomirp** [comment]
I think the issue with the linting can be solved with [this](https://github.com/canonical/template-operator/pull/42/files) change in the tox config.

**Comment by deusebio** [comment]
Cool! Thanks @dragomirp ! Yep, @beliaev-maksim figured it out. We opened a PR for this #31

**Review by marceloneppel — APPROVED** [review]
Looks good!

**Comment by beliaev-maksim** [comment]
@deusebio @dragomirp @marceloneppel 
please merge the PR when ready, I do not have rights

**Comment by marceloneppel** [comment]
> @deusebio @dragomirp @marceloneppel please merge the PR when ready, I do not have rights

Done. Thanks for this update @beliaev-maksim!

**Pull request merged**
